# Generated by Django 5.1.2 on 2025-04-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkup",
            name="departDT",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="checkup",
            name="startDT",
            field=models.DateTimeField(null=True),
        ),
    ]
