# Generated by Django 5.1.2 on 2025-04-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_checkup_departdt_alter_checkup_startdt"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="name",
            field=models.TextField(default="Unnamed"),
        ),
    ]
