# Generated by Django 5.1.2 on 2025-04-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_checkup_inspector"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="depart_datetime",
            field=models.DateTimeField(default=-39),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="checkup",
            name="start_datetime",
            field=models.DateTimeField(default=-39),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="checkup",
            name="status",
            field=models.TextField(default="Pending"),
        ),
    ]
