# Generated by Django 5.1.2 on 2025-04-02 18:22

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_checkup_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="address",
            field=encrypted_model_fields.fields.EncryptedCharField(
                default="108 Central Street"
            ),
            preserve_default=False,
        ),
    ]
