# Generated by Django 5.1.2 on 2025-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_checkup_depart_datetime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="depart_datetime",
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name="checkup",
            name="start_datetime",
            field=models.DateTimeField(default=None),
        ),
    ]
