# Generated by Django 5.1.2 on 2025-04-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_checkup_depart_datetime_checkup_start_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkup",
            name="depart_datetime",
            field=models.DateTimeField(default="placeholder"),
        ),
        migrations.AlterField(
            model_name="checkup",
            name="start_datetime",
            field=models.DateTimeField(default="placeholder"),
        ),
    ]
