# Generated by Django 5.1.2 on 2025-04-02 19:00

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_checkup_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="contact",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True, null=True
            ),
        ),
    ]
