# Generated by Django 5.1.2 on 2025-04-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_checkup_depart_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkup",
            name="depart_datetime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="checkup",
            name="start_datetime",
            field=models.DateTimeField(),
        ),
    ]
