# Generated by Django 5.1.2 on 2025-04-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_checkup_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkup",
            name="name",
            field=models.CharField(default="Unnamed", max_length=50),
        ),
        migrations.AlterField(
            model_name="checkup",
            name="status",
            field=models.CharField(default="Pending", max_length=50),
        ),
    ]
