# Generated by Django 5.1.2 on 2025-04-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_checkup_depart_datetime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checkup",
            name="depart_datetime",
        ),
        migrations.RemoveField(
            model_name="checkup",
            name="start_datetime",
        ),
    ]
