# Generated by Django 5.1.2 on 2025-04-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_alter_checkup_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkup",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
