# Generated by Django 5.1.2 on 2025-04-09 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_customerprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerProfile",
        ),
    ]
