# Generated by Django 5.1.2 on 2025-04-10 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_customerprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
